local map = vim.keymap.set
map("n", "<leader><leader>", function()
  require("snacks").picker.buffers()
end, { desc = "Snacks Search Buffers" })
map("n", "<C-\\>", function()
  require("snacks").picker.explorer()
end, { desc = "Snacks Toggle Explorer" })
map("n", "<leader>se", function()
  require("snacks").picker.explorer()
end, { desc = "Snacks Toggle Explorer" })
map("n", "<leader>sf", function()
  require("snacks").picker.files()
end, { desc = "Snacks Search Files" })
map("n", "<leader>sg", function()
  require("snacks").picker.grep()
end, { desc = "Snacks Search Files by Grep" })
map("n", "<leader>sh", function()
  require("snacks").picker.help()
end, { desc = "Snacks Search Help" })
map("n", "<leader>sk", function()
  require("snacks").picker.keymaps()
end, { desc = "Snacks Search Keymaps" })
map("n", "<leader>sp", function()
  require("snacks").picker.pickers()
end, { desc = "Snacks Search All Pickers" })
map("n", "<leader>sr", function()
  require("snacks").picker.recent()
end, { desc = "Snacks Search Recent Files" })
map({ "n", "t" }, "<A-i>", function()
  require("snacks").terminal.toggle(vim.o.shell)
end, { desc = "Snacks Toggle Terminal" })
